name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: npm Publish / GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install Dependencies
        env:
          CI: true
        run: npm ci
      - name: Build
        if: success()
        env:
          NODE_ENV: production
        run: npm run build
      - name: Test
        if: success()
        run: npm test
      - name: Release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
